services:
  - type: web
    name: car-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: SPREADSHEET_ID
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: LOG_LEVEL
        value: INFO
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
